### ISSUE TITLE
missing $invalidSrcs

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/wgtestui#27]
Error in PHP 8.2
`Error: TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in file /modules/wgtestui/admin/tests.php line 519`

You might need to initiate first:
`$invalidSrcs = [];`

before 

`if ('xoopscore' === $testModule || \array_key_exists($testModule, $moduleslist)) {`

**Comment by ggoffy** [comment]
fixed with https://github.com/XoopsModules25x/wgtestui/pull/28

thank you
